### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Vallerik** [arduino12/mp3_player_module_wire#1]
Good afternoon! Thanks for the library, I compile the "basic_test" example for any Arduino board and get the following error: 
C:\Users\User\AppData\Local\Temp\ccaZrtGn.ltrans0.ltrans.o: In function `setup':

C:\Users\User\AppData\Local\Temp\arduino_modified_sketch_461914/basic_test.ino:30: undefined reference to `Mp3PlayerModuleWire::set_volume(unsigned char)'

collect2.exe: error: ld returned 1 exit status

I can't understand what's wrong?

**Comment by arduino12** [comment]
Hi,

1. How did you installed the library?
2. Which board did you choose?
3. What is your ArduinoIDE version and OS?

I have just download this library from github, unziped into:
`C:\Users\User\Documents\Arduino\libraries\`
And successfully compiled the example to Arduino UNO using Windows ArduinoIDE 1.8.15 :)
